version: '3.7'

services:
  web:
    build: ./leader_final_site
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./leader_final_site:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  nlp:
    build: ./text_processing
    ports:
      - 49490:49490
volumes:
  postgres_data: