# Generated by Django 3.1.3 on 2020-11-28 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups_manager', '0006_1_0_0_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('cls', models.IntegerField(choices=[(1, 'Постоянное поручение'), (2, 'Информационное сообщение'), (3, 'Поручение')], verbose_name='Класс поручения')),
                ('priority', models.IntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')], verbose_name='Приоритет')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок исполнения')),
                ('is_finished', models.BooleanField(blank=True, default=False, verbose_name='Завершено?')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Фактический срок исполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_cards', related_query_name='my_card', to='groups_manager.member', verbose_name='Создатель')),
                ('to_groups', models.ManyToManyField(blank=True, related_name='assigned_cards', related_query_name='assigned_card', to='groups_manager.Group', verbose_name='Группам')),
                ('to_users', models.ManyToManyField(blank=True, related_name='assigned_cards', related_query_name='assigned_card', to='groups_manager.Member')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Тип карточек',
                'verbose_name_plural': 'Типы карточек',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cardtype', verbose_name='Тип поручения'),
        ),
        migrations.AddField(
            model_name='card',
            name='views',
            field=models.ManyToManyField(related_name='cards_viewed', related_query_name='card_viewed', to='groups_manager.Member', verbose_name='Просмотрено?'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reply')),
            ],
        ),
    ]
