# Generated by Django 3.1.3 on 2020-11-28 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups_manager', '0006_1_0_0_default'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='deadline',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Срок исполнения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='cards_viewed', related_query_name='card_viewed', to='groups_manager.Member', verbose_name='Просмотрено?'),
        ),
    ]
