# Generated by Django 3.1.3 on 2020-11-28 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201128_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('cls', models.IntegerField(choices=[(1, 'Постоянное поручение'), (2, 'Информационное сообщение'), (3, 'Поручение')], verbose_name='Класс поручения')),
                ('type', models.IntegerField(choices=[(1, 'Организационное'), (2, 'Технологическое'), (3, 'Техническое')], verbose_name='Тип поручения')),
                ('priority', models.IntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')], verbose_name='Приоритет')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок исполнения')),
                ('is_finished', models.BooleanField(blank=True, default=False, verbose_name='Завершено?')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Фактический срок исполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.card')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reply')),
            ],
        ),
    ]
