# Generated by Django 3.1.3 on 2020-11-29 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups_manager', '0006_1_0_0_default'),
        ('main', '0002_auto_20201128_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groups_manager.member'),
            preserve_default=False,
        ),
    ]
