# Generated by Django 3.1.3 on 2020-11-28 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201128_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='views',
            field=models.ManyToManyField(related_name='users_viewed', related_query_name='user_viewed', to=settings.AUTH_USER_MODEL, verbose_name='Просмотрено?'),
        ),
    ]
