# Generated by Django 3.1.3 on 2020-11-28 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_card_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='views',
            field=models.ManyToManyField(related_name='cards_viewed', related_query_name='card_viewed', to=settings.AUTH_USER_MODEL, verbose_name='Просмотрено?'),
        ),
    ]
