# Generated by Django 3.1.3 on 2020-11-28 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups_manager', '0006_1_0_0_default'),
        ('main', '0010_auto_20201128_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('groups_manager.member',),
        ),
        migrations.AlterField(
            model_name='card',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_cards', related_query_name='my_card', to='main.worker', verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='card',
            name='to_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_cards', related_query_name='assigned_card', to='main.Worker'),
        ),
        migrations.AlterField(
            model_name='card',
            name='views',
            field=models.ManyToManyField(related_name='cards_viewed', related_query_name='card_viewed', to='main.Worker', verbose_name='Просмотрено?'),
        ),
    ]
