# Generated by Django 3.1.3 on 2020-11-28 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201128_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_cards', related_query_name='my_card', to='main.worker', verbose_name='Создатель'),
        ),
    ]
